Improved Simula25 configuration.

diff --git a/make-direct b/make-direct
--- a/make-direct
+++ b/make-direct
@@ -92,7 +92,7 @@ done
 pushd >/dev/null projects
 CONFIG="${PROJECT}.config"
 if [ ! -e "${CONFIG}" ] ; then
-   echo >&2: "ERROR: Project configuration ${CONFIG} not found!"
+   echo >&2 "ERROR: Project configuration ${CONFIG} not found!"
    exit 1
 fi
 PROVISIONERS=""
