Updated scripts.

diff --git a/files/backgrounds/gimp-scripts/gs-caption b/files/backgrounds/gimp-scripts/gs-caption
--- a/files/backgrounds/gimp-scripts/gs-caption
+++ b/files/backgrounds/gimp-scripts/gs-caption
@@ -35,7 +35,7 @@ set -euo pipefail
 # ###### Usage ##############################################################
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 output_filename caption_width caption_height caption_text [-F|--font-name font] [-S|--font-size percentage] [-f|--foreground color] [-b|--background color] [|-t|--transparency percentage] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
+   echo >&2 "Usage: $0 output_filename caption_width caption_height caption_text [-F|--font-name font] [-S|--font-size percentage] [-f|--foreground color] [-b|--background color] [-t|--transparency percentage] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
    exit "${exitCode}"
 }
 
@@ -51,8 +51,15 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o F:S:f:b:t:wqhv --long font-name:,font-size:,foreground:,background:,transparency:,verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -70,64 +77,63 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -F | --font-name)
          FONT_NAME="$2"
-         shift 2
+         shift
          ;;
       -S | --font-size)
          FONT_SIZE="$2"
+         shift
          if [[ ! "${FONT_SIZE}" =~ ^[0-9]+$ ]] || [ "${FONT_SIZE}" -lt 1 ] || [ "${FONT_SIZE}" -gt 100 ] ; then
-            echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -s|--font-size!"
+            echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -S|--font-size!"
             exit 1
          fi
-         shift 2
          ;;
       -f | --foreground)
          COLOR_FOREGROUND="$2"
+         shift
          if [[ ! "${COLOR_FOREGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
             echo >&2 "ERROR: Invalid value ${COLOR_FOREGROUND} for -f|--foreground!"
             exit 1
          fi
-         shift 2
          ;;
       -b | --background)
          COLOR_BACKGROUND="$2"
+         shift
          if [[ ! "${COLOR_BACKGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
             echo >&2 "ERROR: Invalid value ${COLOR_BACKGROUND} for -b|--background!"
             exit 1
          fi
-         shift 2
          ;;
       -t | --transparency)
          TRANSPARENCY="$2"
+         shift
          if [[ ! "${TRANSPARENCY}" =~ ^[0-9]+$ ]] || [ "${TRANSPARENCY}" -lt 0 ] || [ "${TRANSPARENCY}" -gt 100 ]; then
             echo >&2 "ERROR: Invalid value ${TRANSPARENCY} for -t|--transparency!"
             exit 1
          fi
-         TRANSPARENCY="$2"
-         shift 2
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 4 ] ; then
@@ -149,7 +155,7 @@ fi
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+GIMP_CONSOLE="$(command -v gimp-console || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
    echo >&2 "ERROR: GIMP is not installed!"
    echo >&2 "* Ubuntu:  sudo apt install -y gimp"
diff --git a/files/backgrounds/gimp-scripts/gs-mosaic b/files/backgrounds/gimp-scripts/gs-mosaic
--- a/files/backgrounds/gimp-scripts/gs-mosaic
+++ b/files/backgrounds/gimp-scripts/gs-mosaic
@@ -51,8 +51,15 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o T:S:H:N:F:X:I:C:G:A:L:wqhv --long tile-type:,tile-size:,tile-height:,tile-neatness:,tile-surface:,tile-spacing:,tile-allow-split:,color-variation:,color-averaging:,antialiasing:,light-direction:,verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -77,6 +84,7 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -T | --tile-type)
          TILE_TYPESTRING="$2"
+         shift
          if [ "${TILE_TYPESTRING}" = "squares" ] ; then
             TILE_TYPE=0
          elif [ "${TILE_TYPESTRING}" = "hexagons" ] ; then
@@ -89,129 +97,132 @@ while [ $# -gt 0 ] ; do
             echo >&2 "ERROR: Invalid value ${TILE_TYPESTRING} for -T|--tile-type!"
             exit 1
          fi
-         shift 2
          ;;
       -S | --tile-size)
          TILE_SIZE="$2"
+         shift
          if [[ ! "${TILE_SIZE}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($TILE_SIZE < 1.0) || ($TILE_SIZE > 1000.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${TILE_SIZE} for -S|--tile-size!"
             exit 1
          fi
-         shift 2
          ;;
       -H | --tile-height)
          TILE_HEIGHT="$2"
+         shift
          if [[ ! "${TILE_HEIGHT}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($TILE_HEIGHT < 1.0) || ($TILE_HEIGHT > 1000.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${TILE_HEIGHT} for -H|--tile-height!"
             exit 1
          fi
-         shift 2
          ;;
       -N | --tile-neatness)
          TILE_NEATNESS="$2"
+         shift
          if [[ ! "${TILE_NEATNESS}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($TILE_NEATNESS < 0.0) || ($TILE_NEATNESS > 1.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${TILE_NEATNESS} for -N|--tile-neatness!"
             exit 1
          fi
-         shift 2
          ;;
       -F | --tile-surface)
-         if [ "$2" == "smooth" ] ; then
+         TILE_SURFACE="$2"
+         shift
+         if [ "${TILE_SURFACE}" == "smooth" ] ; then
             TILE_SURFACE="FALSE"
-         elif [ "$2" == "rough" ] ; then
+         elif [ "${TILE_SURFACE}" == "rough" ] ; then
             TILE_SURFACE="TRUE"
          else
             echo >&2 "ERROR: Invalid value ${TILE_SURFACE} for -F|--tile-surface!"
             exit 1
          fi
-         shift 2
          ;;
       -I | --tile-allow-split)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         TILE_ALLOW_SPLIT="$2"
+         shift
+         if [[ "${TILE_ALLOW_SPLIT}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             TILE_ALLOW_SPLIT="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${TILE_ALLOW_SPLIT}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             TILE_ALLOW_SPLIT="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -I|--tile-allow-split!"
+            echo >&2 "ERROR: Invalid value ${TILE_ALLOW_SPLIT} for -I|--tile-allow-split!"
             exit 1
          fi
-         shift 2
          ;;
       -X | --tile-spacing)
          TILE_SPACING="$2"
+         shift
          if [[ ! "${TILE_SPACING}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($TILE_SPACING < 0.0) || ($TILE_SPACING > 1000.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${TILE_SPACING} for -X|--tile-spacing!"
             exit 1
          fi
-         shift 2
          ;;
       -C | --color-variation)
          COLOR_VARIATION="$2"
+         shift
          if [[ ! "${COLOR_VARIATION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($COLOR_VARIATION < 0.0) || ($COLOR_VARIATION > 1.0) ? 0 : 1) }" ; then
             echo >&2 "ERROR: Invalid value ${COLOR_VARIATION} for -C|--color-variation!"
             exit 1
          fi
-         shift 2
          ;;
       -G | --color-averaging)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         COLOR_AVERAGING="$2"
+         shift
+         if [[ "${COLOR_AVERAGING}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             COLOR_AVERAGING="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${COLOR_AVERAGING}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             COLOR_AVERAGING="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -g|--color-averaging!"
+            echo >&2 "ERROR: Invalid value ${COLOR_AVERAGING} for -G|--color-averaging!"
             exit 1
          fi
-         shift 2
          ;;
       -A | --antialiasing)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         ANTIALIASING="$2"
+         shift
+         if [[ "${ANTIALIASING}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             ANTIALIASING="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${ANTIALIASING}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             ANTIALIASING="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -A|--antialiasing!"
+            echo >&2 "ERROR: Invalid value ${ANTIALIASING} for -A|--antialiasing!"
             exit 1
          fi
-         shift 2
          ;;
       -L | --light-direction)
          LIGHT_DIRECTION="$2"
+         shift
          if [[ ! "${LIGHT_DIRECTION}" =~ ^([-]{0,1})([0-9]+|[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)$  ]] || \
             awk "BEGIN { exit ( ($LIGHT_DIRECTION < 0.0) || ($LIGHT_DIRECTION > 360.0) ? 0 : 1) }" ; then
-            echo >&2 "ERROR: Invalid value ${LIGHT_DIRECTION} for -C|--light-direction!"
+            echo >&2 "ERROR: Invalid value ${LIGHT_DIRECTION} for -L|--light-direction!"
             exit 1
          fi
-         shift 2
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
@@ -227,7 +238,7 @@ fi
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+GIMP_CONSOLE="$(command -v gimp-console || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
    echo >&2 "ERROR: GIMP is not installed!"
    echo >&2 "* Ubuntu:  sudo apt install -y gimp"
diff --git a/files/backgrounds/gimp-scripts/gs-oilify b/files/backgrounds/gimp-scripts/gs-oilify
--- a/files/backgrounds/gimp-scripts/gs-oilify
+++ b/files/backgrounds/gimp-scripts/gs-oilify
@@ -51,8 +51,15 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o S:I:wqhv --long mask-size:,intensity-mode:,verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -67,46 +74,47 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -S | --mask-size)
          MASK_SIZE="$2"
+         shift
          if [[ ! "${MASK_SIZE}" =~ ^([0-9]+)$ ]] ; then
             echo >&2 "ERROR: Invalid value ${MASK_SIZE} for -S|--mask-size!"
             exit 1
          fi
-         shift 2
          ;;
       -I | --intensity-mode)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         INTENSITY_MODE="$2"
+         shift
+         if [[ "${INTENSITY_MODE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             INTENSITY_MODE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${INTENSITY_MODE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             INTENSITY_MODE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -I|--intensity-mode!"
+            echo >&2 "ERROR: Invalid value ${INTENSITY_MODE} for -I|--intensity-mode!"
             exit 1
          fi
-         shift 2
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
@@ -122,7 +130,7 @@ fi
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+GIMP_CONSOLE="$(command -v gimp-console || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
    echo >&2 "ERROR: GIMP is not installed!"
    echo >&2 "* Ubuntu:  sudo apt install -y gimp"
@@ -179,11 +187,12 @@ rm -f "${OUTPUT_FILENAME}"
    ; GEGL Oilify options: https://gegl.org/operations/gegl-oilify.html
    ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-   (cond( (not(defined? 'plug-in-mosaic))
+   (cond( (not(defined? 'plug-in-oilify))
       ; New GIMP 3.0 API:
       (gimp-drawable-merge-new-filter layer "gegl:oilify" 0 LAYER-MODE-REPLACE 1.0
           "mask-radius" (max 1 (/ maskSize 2))
           "use-inten"   intensityMode
+          "intensities" 128
       )
    )
    (else
diff --git a/files/backgrounds/gimp-scripts/gs-oldphoto b/files/backgrounds/gimp-scripts/gs-oldphoto
--- a/files/backgrounds/gimp-scripts/gs-oldphoto
+++ b/files/backgrounds/gimp-scripts/gs-oldphoto
@@ -51,8 +51,15 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o D:B:S:M:wqhv --long defocus:,border-size:,sepia:,mottle:,verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -68,69 +75,72 @@ VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
       -D | --defocus)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         DEFOCUS="$2"
+         shift
+         if [[ "${DEFOCUS}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             DEFOCUS="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${DEFOCUS}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             DEFOCUS="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -D|--defocus!"
+            echo >&2 "ERROR: Invalid value ${DEFOCUS} for -D|--defocus!"
             exit 1
          fi
-         shift 2
          ;;
       -B | --border-size)
          BORDER_SIZE="$2"
+         shift
          if [[ ! "${BORDER_SIZE}" =~ ^[0-9]+$ ]] ; then
             echo >&2 "ERROR: Invalid value ${BORDER_SIZE} for -B|--border-size!"
             exit 1
          fi
-         shift 2
          ;;
       -S | --sepia)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         SEPIA="$2"
+         shift
+         if [[ "${SEPIA}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             SEPIA="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${SEPIA}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             SEPIA="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -S|--sepia!"
+            echo >&2 "ERROR: Invalid value ${SEPIA} for -S|--sepia!"
             exit 1
          fi
-         shift 2
          ;;
       -M | --mottle)
-         if [[ "$2" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
+         MOTTLE="$2"
+         shift
+         if [[ "${MOTTLE}" =~ ^(on|ON|true|TRUE|yes|YES|1)$ ]] ; then
             MOTTLE="TRUE"
-         elif [[ "$2" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
+         elif [[ "${MOTTLE}" =~ ^(off|OFF|false|FALSE|no|NO|0)$ ]] ; then
             MOTTLE="FALSE"
          else
-            echo >&2 "ERROR: Invalid value $2 for -M|--mottle!"
+            echo >&2 "ERROR: Invalid value ${MOTTLE} for -M|--mottle!"
             exit 1
          fi
-         shift 2
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
@@ -146,7 +156,7 @@ fi
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+GIMP_CONSOLE="$(command -v gimp-console || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
    echo >&2 "ERROR: GIMP is not installed!"
    echo >&2 "* Ubuntu:  sudo apt install -y gimp"
@@ -201,8 +211,14 @@ rm -f "${OUTPUT_FILENAME}"
    (if (not (= RGB imageType))
       (gimp-image-convert-rgb image))
 
-   (script-fu-old-photo image layer
-                        defocus borderSize sepia mottle FALSE)
+   (if (not (defined? 'gimp-image-get-active-layer))
+      (begin ; New GIMP 3.0 API
+         (script-fu-old-photo image (vector layer) defocus borderSize sepia mottle FALSE)
+      )
+      (begin ; Old GIMP 2.x API
+         (script-fu-old-photo image layer defocus borderSize sepia mottle FALSE)
+      )
+   )
 
    ; ------ Save result -----------------------------------------------------
    (if (defined? 'gimp-drawable-merge-new-filter)
diff --git a/files/backgrounds/gimp-scripts/gs-resize-with-cropping b/files/backgrounds/gimp-scripts/gs-resize-with-cropping
--- a/files/backgrounds/gimp-scripts/gs-resize-with-cropping
+++ b/files/backgrounds/gimp-scripts/gs-resize-with-cropping
@@ -51,8 +51,15 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o A:W:H:wqhv --long aspect:,width:,height:,verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -68,27 +75,24 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -A | --aspect)
          ASPECT="$2"
-         shift 2
+         shift
          ;;
       -W | --width)
          NEW_WIDTH="$2"
-         shift 2
+         shift
          ;;
       -H | --height)
          NEW_HEIGHT="$2"
-         shift 2
+         shift
          ;;
       -v | --version)
          version
-         # shift
          ;;
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
@@ -98,9 +102,12 @@ while [ $# -gt 0 ] ; do
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 2 ] ; then
@@ -143,7 +150,7 @@ fi
 
 
 # ====== Detect GraphicsMagick ==============================================
-GM="$(which gm 2>/dev/null || true)"
+GM="$(command -v gm || true)"
 if [ "${GM}" == "" ] ; then
    echo >&2 "ERROR: GraphicsMagick is not installed! Try:"
    echo >&2 " * Ubuntu/Debian: sudo apt install -y graphicsmagick"
diff --git a/files/backgrounds/gimp-scripts/gs-test-gimp b/files/backgrounds/gimp-scripts/gs-test-gimp
--- a/files/backgrounds/gimp-scripts/gs-test-gimp
+++ b/files/backgrounds/gimp-scripts/gs-test-gimp
@@ -51,8 +51,15 @@ version () {
 # ###### Main program #######################################################
 
 # ====== Handle arguments ===================================================
-GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
-# shellcheck disable=SC2068
+if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
+   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
+   exit 1
+fi
+GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
+if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
+   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
+   exit 1
+fi
 options="$(${GETOPT} -o wqhv --long verbose,quiet,help,version -a -- "$@")"
 # shellcheck disable=SC2181
 if [[ $? -ne 0 ]]; then
@@ -66,27 +73,27 @@ while [ $# -gt 0 ] ; do
    case "$1" in
       -w | --verbose)
          VERBOSE=1
-         shift
          ;;
       -q | --quiet)
          VERBOSE=0
-         shift
          ;;
       -h | --help)
          usage 0
          ;;
       -v | --version)
          version
-         # shift
          ;;
       --)
          shift
          break
          ;;
       *)
-         usage 1
+         # This should not happen: wrong getopt parameters, or missing case?
+         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
+         exit 1
          ;;
   esac
+  shift
 done
 
 if [ $# -ne 0 ] ; then
@@ -114,7 +121,7 @@ fi
 
 
 # ====== Detect GIMP, and determine version-specific call options ===========
-GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
+GIMP_CONSOLE="$(command -v gimp-console || true)"
 if [ "${GIMP_CONSOLE}" == "" ] ; then
    echo >&2 "ERROR: GIMP is not installed!"
    echo >&2 "* Ubuntu:  sudo apt install -y gimp"
