Another set of small code improvements and clean-ups.

diff --git a/scripts/11-system-info b/scripts/11-system-info
--- a/scripts/11-system-info
+++ b/scripts/11-system-info
@@ -19,6 +19,18 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
+set -euo pipefail
+
+
+# ====== Print script name, to make Packer output easier readable ===========
+if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
+   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▀" "█\e[0m"
+   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;34m█\e[22m" "\e[1;34m█\e[0m"
+   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▄" "█\e[0m"
+else
+   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
+fi
+
 set -euxo pipefail
 
 
@@ -33,5 +45,11 @@ else
    systemInfoDirectory="/etc/system-info.d"
 fi
 
-find /tmp/system-info -type f -print0 | xargs -r -0 -I "{}" chmod +x "{}"
-find /tmp/system-info -type f -print0 | xargs -r -0 -I "{}" cp "{}" "${systemInfoDirectory}"
+if [ -d /tmp/system-info ] ; then
+   mkdir -p "${systemInfoDirectory}"
+   find /tmp/system-info -type f -exec chmod +x {} \;
+   find /tmp/system-info -type f -exec cp {} "${systemInfoDirectory}/" \;
+else
+   echo >&2 "ERROR: /tmp/system-info does not exist!"
+   exit 1
+fi
diff --git a/scripts/12-configure-grub b/scripts/12-configure-grub
--- a/scripts/12-configure-grub
+++ b/scripts/12-configure-grub
@@ -19,6 +19,18 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
+set -euo pipefail
+
+
+# ====== Print script name, to make Packer output easier readable ===========
+if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
+   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▀" "█\e[0m"
+   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;34m█\e[22m" "\e[1;34m█\e[0m"
+   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▄" "█\e[0m"
+else
+   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
+fi
+
 set -euxo pipefail
 
 
@@ -40,12 +52,18 @@ if [ "${UNAME}" == "Linux" ] ; then
       # from tmp/. They should have been placed there by the file provisioner.
       if [ ! -e "${BOOTSPLASH}" ] ; then
          dir="$(dirname "${BOOTSPLASH}")"
-         sudo mkdir -p "${dir}/"
-         sudo mv "/tmp/bootsplash-images/$(basename "${BOOTSPLASH}")" "${dir}/"
+         mkdir -p "${dir}/"
+         tmpBootsplashFile="/tmp/bootsplash-images/$(basename "${BOOTSPLASH}")"
+         if [ -e "${tmpBootsplashFile}" ] ; then
+            mv "${tmpBootsplashFile}" "${dir}/"
+         else
+            echo >&2 "ERROR: Bootsplash file ${BOOTSPLASH} not found locally or in /tmp/bootsplash-images!"
+            exit 1
+         fi
       fi
 
       loader=""
-      if [[ "${BOOTSPLASH}" =~ (\.[Jj][Pp][Ee][Gg]|\.[Jj][Pp][Ee][Gg])$ ]] ; then
+      if [[ "${BOOTSPLASH}" =~ (\.[Jj][Pp][Ee][Gg]|\.[Jj][Pp][Gg])$ ]] ; then
          loader="jpeg"
       elif [[ "${BOOTSPLASH}" =~ (\.[Pp][Nn][Gg])$ ]] ; then
          loader="png"
@@ -56,11 +74,16 @@ if [ "${UNAME}" == "Linux" ] ; then
          exit 1
       fi
       if [ -d /etc/grub.d ] && [ -e /etc/default/grub ] ;  then
-         sed -e "s%@SET_BOOTSPLASH_HERE@%${BOOTSPLASH}%g" \
-             -e "s%@SET_LOADER_HERE@%${loader}%g" \
-            </tmp/configuration-files/06_aaaaa_bootsplash.in >/etc/grub.d/06_aaaaa_bootsplash
-         chmod +x /etc/grub.d/06_aaaaa_bootsplash
-         configure-grub /usr/share/configure-grub/grub-defaults-nornet -o /etc/default/grub
+         templateFile="/tmp/configuration-files/06_aaaaa_bootsplash.in"
+         if [ -e "${templateFile}" ] ; then
+            sed -e "s%@SET_BOOTSPLASH_HERE@%${BOOTSPLASH}%g" \
+                -e "s%@SET_LOADER_HERE@%${loader}%g" \
+                <"${templateFile}" >/etc/grub.d/06_aaaaa_bootsplash
+            chmod +x /etc/grub.d/06_aaaaa_bootsplash
+         else
+            echo >&2 "ERROR: Bootsplash configuration template ${templateFile} is missing!"
+            exit 1
+         fi
       fi
    fi
 
@@ -70,11 +93,11 @@ if [ "${UNAME}" == "Linux" ] ; then
          configure-grub /usr/share/configure-grub/grub-defaults-nornet \
             -V "auto,${VIDEO},1024x768" \
             -o /etc/default/grub
-         if command -v grub2-mkconfig 2>/dev/null ; then
-            grub2-mkconfig -o /boot/grub2/grub.cfg || true
-         else
-            update-grub || true
-         fi
+      fi
+      if command -v grub2-mkconfig 2>/dev/null ; then
+         grub2-mkconfig -o /boot/grub2/grub.cfg || true
+      else
+         update-grub || true
       fi
    fi
 
