Improved SimulaMet configuration.

diff --git a/scripts/11-system-info b/scripts/11-system-info
--- a/scripts/11-system-info
+++ b/scripts/11-system-info
@@ -59,11 +59,15 @@ else
    systemInfoDirectory="/etc/system-info.d"
 fi
 
-if [ -d /tmp/system-info ] ; then
+# This directory is created by the configurations in ../files/$0
+# Make sure that the corresponding configuration exists there!
+INPUT_DIRECTORY="/tmp/system-info"
+
+if [ -d "${INPUT_DIRECTORY}" ] ; then
    mkdir -p "${systemInfoDirectory}"
-   find /tmp/system-info -type f -exec chmod +x {} \;
-   find /tmp/system-info -type f -exec cp {} "${systemInfoDirectory}/" \;
+   find "${INPUT_DIRECTORY}" -type f -exec chmod +x {} \;
+   find "${INPUT_DIRECTORY}" -type f -exec cp {} "${systemInfoDirectory}/" \;
 else
-   echo >&2 "ERROR: /tmp/system-info does not exist!"
+   echo >&2 "ERROR: ${INPUT_DIRECTORY} does not exist!"
    exit 1
 fi
