Further clean-ups.

diff --git a/scripts/22-configure-wireshark b/scripts/22-configure-wireshark
--- a/scripts/22-configure-wireshark
+++ b/scripts/22-configure-wireshark
@@ -19,11 +19,24 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
-set -euxo pipefail
+set -euo pipefail
 
 
 # NOTE:
 # Non-root user permission will be given in 38-allow-wireshark-as-user, not here!
+
+
+# ====== Print script name, to make Packer output easier readable ===========
+if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
+   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▀" "█\e[0m"
+   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;32m█\e[22m" "\e[1;32m█\e[0m"
+   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▄" "█\e[0m"
+else
+   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
+fi
+
+# Enable printing the command-lines executed:
+set -x
 
 
 # ====== Check environment variables ========================================
@@ -32,12 +45,34 @@ if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
    echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
    exit 1
 fi
+USER_GROUP="$(id -gn "${USER_NAME}")"
+USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6 || awk -F: -v user="${USER_NAME}" '$1==user { print $6 }' /etc/passwd)"
+UNAME="$(uname)"
 
 
 # ====== Wireshark filter rules =============================================
-mkdir -p /root/.config/wireshark
-sudo -u "${USER_NAME}" mkdir -p "/home/${USER_NAME}/.config/wireshark"
-for file in colorfilters decode_as_entries dfilters preferences ; do
-   cp "/tmp/wireshark/${file}"                        /root/.config/wireshark
-   sudo -u "${USER_NAME}" cp "/tmp/wireshark/${file}" "/home/${USER_NAME}/.config/wireshark"
-done
+if [ -d /tmp/wireshark ] ; then
+   skelDirectory="/etc/skel"
+   if [ "${UNAME}" == "FreeBSD" ] ; then
+      skelDirectory="/usr/share/skel"
+   fi
+
+   mkdir -p /root/.config/wireshark
+   mkdir -p "${USER_HOME}/.config/wireshark"
+   mkdir -p "${skelDirectory}/.config/wireshark"
+
+   for configurationFile in colorfilters decode_as_entries dfilters preferences ; do
+      sourceConfigurationFile="/tmp/wireshark/${configurationFile}"
+      if [ -e "${sourceConfigurationFile}" ] ; then
+         cp "${sourceConfigurationFile}" /root/.config/wireshark/
+         cp "${sourceConfigurationFile}" "${USER_HOME}/.config/wireshark/"
+         cp "${sourceConfigurationFile}" "${skelDirectory}/.config/wireshark/"
+      else
+         echo >&2 "WARNING: Source Wireshark configuration file ${sourceConfigurationFile} is missing!"
+      fi
+   done
+   chown -R "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.config/wireshark"
+else
+   echo >&2 "ERROR: Source directory /tmp/wireshark does not exist!"
+   exit 1
+fi
