Minor clean-ups.

diff --git a/scripts/71-deepfakeecg b/scripts/71-deepfakeecg
--- a/scripts/71-deepfakeecg
+++ b/scripts/71-deepfakeecg
@@ -32,6 +32,25 @@
 set -euo pipefail
 
 
+# ###### Ensure that script is executed by the user account #################
+if [ "$(id -u)" -eq 0 ] ; then
+   # Running as root using sudo. Run the script again, but as user!
+   echo "Running as ROOT! SUDO_USER=${SUDO_USER}"
+   if [ "${SUDO_USER}" != "root" ] ; then
+      # shellcheck disable=SC2068
+      sudo -u "${SUDO_USER}" "$0" $@ && exit 0
+      exit 1
+   else
+      # Prevent recursive invocation as "root" user:
+      echo >&2 "ERROR: Run this script either as user or with sudo."
+      exit 1
+   fi
+else
+   # Echo running as user
+   echo "Running as ${USER}! SUDO_USER=${SUDO_USER:-}"
+fi
+
+
 # ###### Print script name, to make Packer output easier readable ###########
 if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
    echo
@@ -75,31 +94,11 @@ fi
 UNAME="$(uname)"
 
 
-# ====== Ensure that script is executed by the user account =================
-if [ "$(id -u)" -eq 0 ] ; then
-   # Running by configuring sudo root. Run script again, but as user!
-   echo "Running as ROOT! SUDO_USER=${SUDO_USER}"
-   if [ "${SUDO_USER}" != "root" ] ; then
-      # shellcheck disable=SC2068
-      sudo -u "${SUDO_USER}" "$0" $@ && exit 0
-      exit 1
-   else
-      # Prevent recursive invocation as "root" user:
-      echo >&2 "ERROR: Run this script either as user or with sudo."
-      exit 1
-   fi
-else
-   # Echo running as user
-   echo "Running as ${USER}! SUDO_USER=${SUDO_USER:-}"
-fi
-
-
 # ====== Prepare directories ================================================
 mkdir -p "${HOME}/Desktop"
 mkdir -p "${HOME}/src"
 mkdir -p "${HOME}/python-environments"
 cd "${HOME}/src"
-
 
 # ====== DeepFakeECG Generator Plus =========================================
 if [ "${UNAME}" == "Linux" ] ; then
