Further script clean-ups.

diff --git a/scripts/81-prepare-5gVINNI-sources b/scripts/81-prepare-5gVINNI-sources
--- a/scripts/81-prepare-5gVINNI-sources
+++ b/scripts/81-prepare-5gVINNI-sources
@@ -19,26 +19,60 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
-set -euxo pipefail
+set -euo pipefail
 
 
-# ====== Ensure that script is ran by user account to provision =============
-if [ "$(id -u)" -eq 0 ] ; then
-   # Running by configuring sudo root. Run script again, but as user!
-   echo "Running as ROOT! SUDO_USER=${SUDO_USER}"
-   if [ "${SUDO_USER}" != "root" ] ; then
-      # shellcheck disable=SC2068
-      sudo -u "${SUDO_USER}" "$0" $@ && exit 0
-      exit 1
-   else
-      # Prevent recursive invocation as "root" user:
-      echo >&2 "ERROR: Run this script either as user or with sudo."
-      exit 1
-   fi
+# ====== Print script name, to make Packer output easier readable ===========
+if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
+   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;35m█" "▀" "█\e[0m"
+   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;35m█\e[22m" "\e[1;35m█\e[0m"
+   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;35m█" "▄" "█\e[0m"
 else
-   # Echo running as user
-   echo "Running as ${USER}! SUDO_USER=${SUDO_USER}"
+   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
 fi
+
+# Enable printing the command-lines executed:
+set -x
+
+
+# ###### Clone or update Git repository #####################################
+clone-or-update ()
+{
+   local repository="$1"
+   local url="$2"
+   local clone_maxtrials=10
+   local clone_delay=60
+   if [ ! -e "${repository}" ] ; then
+      try-hard ${clone_maxtrials} ${clone_delay} -- sudo -u "${USER_NAME}" git clone "${url}" "${repository}"
+   else
+      pushd "${repository}" >/dev/null
+      try-hard ${clone_maxtrials} ${clone_delay} -- sudo -u "${USER_NAME}" git fetch --all
+      try-hard ${clone_maxtrials} ${clone_delay} -- sudo -u "${USER_NAME}" git pull
+      popd >/dev/null
+   fi
+}
+
+
+# ====== Check environment variables ========================================
+if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
+   echo >&2 "Usage: env USER_NAME=<user> $0"
+   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
+   exit 1
+fi
+USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6 || awk -F: -v user="${USER_NAME}" '$1==user { print $6 }' /etc/passwd)"
+
+if [ ! -e /etc/os-release ] ; then
+   echo >&2 "ERROR: /etc/os-release is not available!"
+   exit 1
+fi
+. /etc/os-release
+
+
+# ====== Prepare source repositories ========================================
+sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/src"
+cd "${USER_HOME}/src"
+
+clone-or-update 5gvinni-oai-ns   https://github.com/simula/5gvinni-oai-ns.git
 
 
 # ====== Make some additions to .bashrc =====================================
@@ -47,16 +81,3 @@ cat >>.bashrc <<EOF
 # Change prompt colours, to make it easier to notice being logged into a VM.
 PS1='\${debian_chroot:+(\$debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;39m\]\w\[\033[00m\]\\$ '
 EOF
-
-
-# ====== Prepare source repositories ========================================
-mkdir -p ~/src
-cd ~/src
-
-# NOTE: The repositories are not cloned here!
-
-mkdir -p 5gvinni-oai-ns
-pushd 5gvinni-oai-ns
-git init
-git remote add origin https://github.com/simula/5gvinni-oai-ns.git
-popd
